[project]
name = "betata"
version = "0.1.0"
description = "Scripts to analyze data collected for the beta Ta paper."
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
]
